GET http://localhost:8081/v2/employees
Accept: application/json

###
GET http://localhost:8081/v2/schedule
Accept: application/json

###
POST http://localhost:8081/v2/employees
Content-Type: application/json

{"name": "craig",
  "title":  "developer",
  "department":  "research"}

###